apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs
  minReplicas: 7
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 50
        name: memory
        targetAverageUtilization: 60
      type: Resource
